[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = "../tools/qemu-run"

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
