#!/bin/bash

set -eu

BASE_ADDR=0x80000

export CARGO_BUILD_RUSTFLAGS="\
	-Ccode-model=large \
	-Crelocation-model=static \
	-Clink-arg=--image-base=${BASE_ADDR} \
	-Clink-arg=--section-start=.entry=${BASE_ADDR} \
	-Clink-arg=--nmagic"
export CARGO_BUILD_TARGET="aarch64-unknown-none"
export CARGO_UNSTABLE_BUILD_STD="core"
export CARGO_TARGET_AARCH64_UNKNOWN_NONE_RUNNER="scripts/qemu-run"

exec cargo "$@"
