#!/bin/bash

set -eu

if [ $# -lt 1 ]; then
	echo "usage: qemu-run kernel [qemu_flags]" >&2
	exit 2
fi
kernel=$1
shift

kernel_flat="$kernel.flat"

out=$(flatelf "${kernel}" "${kernel_flat}")
base_vaddr=$(echo "${out}" | cut -d ' ' -f 1)
entry=$(echo "${out}" | cut -d ' ' -f 2)
size=$(echo "${out}" | cut -d ' ' -f 3)

echo "Base address: ${base_vaddr}"
echo "Entry point: ${entry}"
echo "Size: ${size}"
echo '---'

dtb="$(dirname $0)/bcm2710-rpi-3-b.dtb"

qemu-system-aarch64 \
	-nodefaults \
	-nographic \
	-cpu cortex-a53 \
	-M raspi3b \
	-dtb "${dtb}" \
	-serial mon:stdio \
	-kernel "${kernel_flat}" \
	"$@"
